apiVersion: apps/v1
kind: Deployment
metadata:
   name: carwebdeployment
spec:
  selector:
    matchLables:
      app: car
  templates:
    metadata:
      labels:
        app: car
    spec:
    - containers:
      name: carimage
      image: devopschand/carweb
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: carsvc
spec:
  type: NodePort
  selector:
    app: car
  ports:
  - port: 80
    targetPort: 80


